import {
    IconBrandReact,
    IconBrandTypescript,
    IconBrandNextjs,
    IconBrandPython,
    IconDiamond,
    IconBrandCss3,
    IconBrandCSharp,
    IconSql,
    IconBrandAws,
    IconBrandJavascript,
    IconBrandNodejs,
    IconBrandTailwind,
  } from "@tabler/icons-react";

export const skills = [
    {
      language: "Python",
      icon: <IconBrandPython height={150} width={150} />,
      styling: "text-pythonYellow bg-pythonBlue hover:text-pythonBlue hover:bg-pythonYellow ease-in-out duration-300 h-64 lg:h-80 w-60 lg:w-72",
      position: "end",
      order: "order-2",
      textOrder: "order-1",
      transition: 1,
    },
    {
      language: "C#",
      icon: <IconBrandCSharp height={150} width={150} />,
      styling: "text-white bg-cSharpPurple hover:text-cSharpPurple hover:bg-white ease-in-out duration-300 h-64 lg:h-80 w-60 lg:w-72",
      position: "end",
      order: "order-2",
      textOrder: "order-1",
      transition: 2,
    },
    {
      language: "Ruby on Rails",
      icon: <IconDiamond height={150} width={150} />,
      styling: "text-white bg-rubyRed hover:text-rubyRed hover:bg-white ease-in-out duration-300 h-64 lg:h-80 w-60 lg:w-72",
      position: "start",
      order: "order-1",
      textOrder: "order-2",
      transition: 2.5,
    },
    {
      language: "Javascript",
      icon: <IconBrandJavascript height={150} width={150} />,
      styling: "text-black bg-jsYellow hover:text-jsYellow hover:bg-black ease-in-out duration-300 h-64 lg:h-80 w-60 lg:w-72",
      position: "end",
      order: "order-2",
      textOrder: "order-1",
      transition: 3,
    },
    {
      language: "React.js",
      icon: <IconBrandReact height={150} width={150} />,
      styling: "text-reactBlue bg-reactGrey hover:text-reactGrey hover:bg-reactBlue ease-in-out duration-300 h-64 lg:h-80 w-60 lg:w-72",
      position: "end",
      order: "order-2",
      textOrder: "order-1",
      transition: 3.5,
    },
    {
      language: "Typescript",
      icon: <IconBrandTypescript height={150} width={150} />,
      styling: "text-white bg-sqlBlue hover:text-sqlBlue hover:bg-white ease-in-out duration-300 h-64 lg:h-80 w-60 lg:w-72",
      position: "end",
      order: "order-2",
      textOrder: "order-1",
      transition: 4,
    },
    {
      language: "Next.js",
      icon: <IconBrandNextjs height={150} width={150} />,
      styling: "text-white bg-black hover:text-black hover:bg-white ease-in-out duration-300 h-64 lg:h-80 w-60 lg:w-72",
      position: "end",
      order: "order-2",
      textOrder: "order-1",
      transition: 4.5,
    },
    {
      language: "Node.js",
      icon: <IconBrandNodejs height={150} width={150} />,
      styling: "text-nodeGreen bg-nodeBlue hover:text-nodeBlue hover:bg-nodeGreen ease-in-out duration-300 h-64 lg:h-80 w-60 lg:w-72",
      position: "end",
      order: "order-2",
      textOrder: "order-1",
      transition: 5,
    },
    {
      language: "AWS",
      icon: <IconBrandAws height={150} width={150} />,
      styling: "text-awsOrange bg-awsBlue hover:text-awsBlue hover:bg-awsOrange ease-in-out duration-300 h-64 lg:h-80 w-60 lg:w-72",
      position: "end",
      order: "order-2",
      textOrder: "order-1",
      transition: 5.5,
    },
    {
      language: "Tailwind",
      icon: <IconBrandTailwind height={150} width={150} />,
      styling: "text-tailWLightBlue bg-tailWBlue hover:text-tailWBlue hover:bg-tailWLightBlue ease-in-out duration-300 h-64 lg:h-80 w-60 lg:w-72",
      position: "end",
      order: "order-2",
      textOrder: "order-1",
      transition: 6,
    },
    {
      language: "CSS3",
      icon: <IconBrandCss3 height={150} width={150} />,
      styling: "text-white bg-cssBlue hover:text-cssBlue hover:bg-white ease-in-out duration-300 h-64 lg:h-80 w-60 lg:w-72",
      position: "end",
      order: "order-2",
      textOrder: "order-1",
      transition: 6.5,
    },
    {
      language: "SQL",
      icon: <IconSql height={150} width={150} />,
      styling: "text-white bg-sqlBlue hover:text-sqlBlue hover:bg-white ease-in-out duration-300 h-64 lg:h-80 w-60 lg:w-72",
      position: "end",
      order: "order-2",
      textOrder: "order-1",
      transition: 7,
    },
  ];