import type { Metadata } from "next";
import { Oswald, Roboto } from "next/font/google";
import "./globals.css";
import Sidebar from './component/Sidebar'

const roboto = Roboto({ 
  subsets: ["latin"],
  weight: '300'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
